// 잼라이브 기출문제 기반 퀴즈 문제
// type: 'multiple' (4지선다) | 'triple' (3지선다) | 'ox' (O/X)

const questions = [
  {
    id: 1,
    type: 'triple',
    question: '닌텐도는 원래 무엇을 만들던 회사였을까?',
    choices: ['화투', '봉제인형', '편지지'],
    answer: 0,
    timeLimit: 15,
  },
  {
    id: 2,
    type: 'triple',
    question: '호주의 수도는?',
    choices: ['시드니', '멜버른', '캔버라'],
    answer: 2,
    timeLimit: 12,
  },
  {
    id: 3,
    type: 'triple',
    question: '유니콘처럼 반짝 성공했다가 망한 스타트업 기업을 일컫는 말은?',
    choices: ['유니콥스', '유니클로', '유니세프'],
    answer: 0,
    timeLimit: 15,
  },
  {
    id: 4,
    type: 'triple',
    question: '자신이 좋아하는 분야에서 성공한 사람을 뜻하는 신조어는?',
    choices: ['지덕', '후덕', '성덕'],
    answer: 2,
    timeLimit: 12,
  },
  {
    id: 5,
    type: 'ox',
    question: '대부분의 치킨은 왼쪽 다리가 더 쫄깃하다',
    choices: ['O', 'X'],
    answer: 0,
    timeLimit: 10,
  },
  {
    id: 6,
    type: 'triple',
    question: '우리나라가 가장 많이 수입하는 자원은?',
    choices: ['철광석', '석유', '고무'],
    answer: 1,
    timeLimit: 12,
  },
  {
    id: 7,
    type: 'triple',
    question: '외부와 단절된 혼자만의 공간에서 안락함을 추구하는 사람을 일컫는 용어는?',
    choices: ['코쿤족', '딩크족', '니트족'],
    answer: 0,
    timeLimit: 15,
  },
  {
    id: 8,
    type: 'triple',
    question: '호박, 구두, 왕자님 — 이 단어들에서 연상되는 동화 주인공은?',
    choices: ['백설공주', '인어공주', '신데렐라'],
    answer: 2,
    timeLimit: 12,
  },
  {
    id: 9,
    type: 'triple',
    question: '2016년 리우 올림픽에서 정식 종목으로 새롭게 채택된 것은?',
    choices: ['비치발리볼', '주짓수', '골프'],
    answer: 2,
    timeLimit: 15,
  },
  {
    id: 10,
    type: 'triple',
    question: '한 달에 두 번 뜨는 보름달을 무엇이라 부를까?',
    choices: ['럭키문', '블루문', '더블문'],
    answer: 1,
    timeLimit: 12,
  },
  {
    id: 11,
    type: 'triple',
    question: '익명이라는 뜻을 가진 글로벌 해커 집단의 이름은?',
    choices: ['리자드 스쿼드', '수어사이드 스쿼드', '어나니머스'],
    answer: 2,
    timeLimit: 15,
  },
  {
    id: 12,
    type: 'triple',
    question: '뉴노멀(New Normal)의 중국식 표현으로 올바른 것은?',
    choices: ['무에타이', '신창타이', '전선타이'],
    answer: 1,
    timeLimit: 15,
  },
  {
    id: 13,
    type: 'triple',
    question: '단군 신화를 최초로 기록한 역사서는?',
    choices: ['구삼국사', '삼국사기', '삼국유사'],
    answer: 2,
    timeLimit: 15,
  },
  {
    id: 14,
    type: 'ox',
    question: '짜장면과 자장면은 둘 다 표준어로 인정된다',
    choices: ['O', 'X'],
    answer: 0,
    timeLimit: 10,
  },
  {
    id: 15,
    type: 'triple',
    question: '주식이나 채권을 보유하지 않은 상태에서 매도하는 것을 무엇이라 할까?',
    choices: ['가매도', '반매도', '공매도'],
    answer: 2,
    timeLimit: 15,
  },
  {
    id: 16,
    type: 'triple',
    question: '높은 사회적 신분에 따르는 도덕적 의무를 뜻하는 말은?',
    choices: ['노블레스 오블리주', '카르페 디엠', '메멘토 모리'],
    answer: 0,
    timeLimit: 15,
  },
  {
    id: 17,
    type: 'triple',
    question: '순우리말로 \'된바람\'은 어느 방향에서 부는 바람일까?',
    choices: ['동쪽', '서쪽', '북쪽'],
    answer: 1,
    timeLimit: 15,
  },
  {
    id: 18,
    type: 'triple',
    question: '국내 사이버 민간 외교관 역할을 하는 사이버 외교사절단의 이름은?',
    choices: ['뭉크', '라크', '반크'],
    answer: 2,
    timeLimit: 15,
  },
  {
    id: 19,
    type: 'triple',
    question: '다음 중 돼지고기 부위는?',
    choices: ['우둔살', '갈매기살', '제비추리'],
    answer: 1,
    timeLimit: 15,
  },
  {
    id: 20,
    type: 'ox',
    question: '코끼리와 쥐의 몸 크기 차이는 세포의 수가 아니라 세포의 크기 차이 때문이다',
    choices: ['O', 'X'],
    answer: 1,
    timeLimit: 12,
  },
  {
    id: 21,
    type: 'triple',
    question: '물건의 단단한 정도를 나타내는 단어는?',
    choices: ['강도', '인성', '경도'],
    answer: 2,
    timeLimit: 15,
  },
  {
    id: 22,
    type: 'triple',
    question: '다음 중 지명에서 유래된 음식이 아닌 것은?',
    choices: ['체다치즈', '햄버거', '퐁듀'],
    answer: 2,
    timeLimit: 15,
  },
];

module.exports = questions;
